In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv("Social_Network_Ads.csv")
df

User ID  Age  EstimatedSalary  Purchased
0    15624510   19            19000          0
1    15810944   35            20000          0
2    15668575   26            43000          0
3    15603246   27            57000          0
4    15804002   19            76000          0
..        ...  ...              ...        ...
395  15691863   46            41000          1
396  15706071   51            23000          1
397  15654296   50            20000          1
398  15755018   36            33000          0
399  15594041   49            36000          1

[400 rows x 4 columns]

In [ ]:
x = df.drop(['Purchased'],axis=1)
y = df['Purchased']

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.25,random_state=42)

In [ ]:
from sklearn.svm import SVC
svc_model = SVC(kernel="rbf")
svc_model

SVC()

In [ ]:
svc_model.fit(x_train,y_train)

SVC()

In [ ]:
y_pred = svc_model.predict(x_test)
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
from sklearn import metrics
metrics.accuracy_score(y_test,y_pred)

0.63

In [ ]:
from sklearn.svm import SVC
svc_model1 = SVC(kernel="poly")
svc_model1.fit(x_train,y_train)

SVC(kernel='poly')

In [ ]:
y_pred1 = svc_model1.predict(x_test)
y_pred1

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
from sklearn import metrics
metrics.accuracy_score(y_test,y_pred1)

0.63

In [ ]:
from sklearn.svm import SVC
svc_model2 = SVC(kernel="linear")
svc_model2.fit(x_train,y_train)

SVC(kernel='linear')

In [ ]:
y_pred2 = svc_model2.predict(x_test)
y_pred2

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1])

In [ ]:
metrics.accuracy_score(y_test,y_pred2)

0.73

# **Apply Hyper parameter tuning on k-nearest neighbour classifier**

In [ ]:
df = pd.read_csv("Iris.csv")
df

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

In [ ]:
x = df.drop(['Species'],axis=1)
y = df['Species']

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
KNN1 = KNeighborsClassifier(n_neighbors=2)
KNN1

KNeighborsClassifier(n_neighbors=2)

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=2,random_state=42)

In [ ]:
KNN1.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=2)

In [ ]:
from sklearn.svm import SVC
svc_model = SVC(kernel="rbf")
svc_model

SVC()

In [ ]:
svc_model.fit(x_train,y_train)

SVC()

In [ ]:
y_pred = svc_model.predict(x_test)
y_pred

array(['Iris-versicolor', 'Iris-setosa'], dtype=object)

In [ ]:
from sklearn.svm import SVC
svc_model1 = SVC(kernel="poly")
svc_model1.fit(x_train,y_train)

SVC(kernel='poly')

In [ ]:
y_pred1 = svc_model1.predict(x_test)
y_pred1

array(['Iris-versicolor', 'Iris-setosa'], dtype=object)

In [ ]:
from sklearn import metrics
metrics.accuracy_score(y_test,y_pred1)

1.0

In [ ]:
from sklearn.svm import SVC
svc_model2 = SVC(kernel="linear")
svc_model2.fit(x_train,y_train)

SVC(kernel='linear')

In [ ]:
y_pred2 = svc_model2.predict(x_test)
y_pred2

array(['Iris-versicolor', 'Iris-setosa'], dtype=object)

In [ ]:
metrics.accuracy_score(y_test,y_pred2)

1.0

# **Parameter Gamma**

In [ ]:
from sklearn.svm import SVC
svcmodel = SVC(kernel='rbf',gamma=15,C=7)
svcmodel.fit(x_train,y_train)
y_pred3 = svcmodel.predict(x_test)
metrics.accuracy_score(y_test,y_pred)

1.0

In [ ]:
from sklearn.svm import SVC
svcmodel = SVC(kernel='rbf',gamma=1,C=7)
svcmodel.fit(x_train,y_train)
y_pred3 = svcmodel.predict(x_test)
metrics.accuracy_score(y_test,y_pred)

1.0

In [ ]:
y_pred3 = svc_model1.predict(x_test)
y_pred3

array(['Iris-versicolor', 'Iris-setosa'], dtype=object)

# **Assignment**

Perform the following acitivity using iloc-

x = df.drop(['Purchased'],axis=1)

y = df['Purchased']

# **iloc() Function**
Syntax:  df.iloc[row_start:row_end, column_start:column_end]

The iloc() function provides a straightforward and intuitive way to access specific rows and columns in a pandas DataFrame using integer-based indexing. It allows you to locate and retrieve data based on its position within the DataFrame, rather than relying on labels or names.

In [ ]:
#iloc() Function : df.iloc[row_start:row_end, column_start:column_end]
x=df.iloc[ : , :3]
x

Id  SepalLengthCm  SepalWidthCm
0      1            5.1           3.5
1      2            4.9           3.0
2      3            4.7           3.2
3      4            4.6           3.1
4      5            5.0           3.6
..   ...            ...           ...
145  146            6.7           3.0
146  147            6.3           2.5
147  148            6.5           3.0
148  149            6.2           3.4
149  150            5.9           3.0

[150 rows x 3 columns]

In [ ]:
y=df.iloc[ : , 3:]
y

PetalLengthCm  PetalWidthCm         Species
0              1.4           0.2     Iris-setosa
1              1.4           0.2     Iris-setosa
2              1.3           0.2     Iris-setosa
3              1.5           0.2     Iris-setosa
4              1.4           0.2     Iris-setosa
..             ...           ...             ...
145            5.2           2.3  Iris-virginica
146            5.0           1.9  Iris-virginica
147            5.2           2.0  Iris-virginica
148            5.4           2.3  Iris-virginica
149            5.1           1.8  Iris-virginica

[150 rows x 3 columns]

In [ ]:
# SVM code on iris dataset
# Apply Hyper parameter tuning on k-Nearest Neighbour classifier
import pandas as pd
import numpy as np
data=pd.read_csv("Iris.csv")
df_iris=pd.DataFrame(data)
df_iris

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

In [ ]:
x_iris=df_iris.drop(['Species'],axis=1)
x_iris

y_iris=df_iris['Species']
y_iris

0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...      
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
Name: Species, Length: 150, dtype: object

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
IrisNN = KNeighborsClassifier(n_neighbors=4)
IrisNN

KNeighborsClassifier(n_neighbors=4)

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x_iris,y_iris)

In [ ]:
Iris_Classifier = IrisNN.fit(x_train,y_train)

from sklearn.svm import SVC
i_svmodel=SVC(kernel='rbf',gamma=15,C=7)
i_svmodel.fit(x_train,y_train)


SVC(C=7, gamma=15)

In [ ]:
y_pred=i_svmodel.predict(x_test)
y_pred


array(['Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor'], dtype=object)

In [ ]:
from sklearn import metrics
metrics.accuracy_score(y_test,y_pred)

0.2631578947368421

In [ ]:
from sklearn.svm import SVC
svmodel2=SVC(kernel='linear')
svmodel2.fit(x_train,y_train)

SVC(kernel='linear')

In [ ]:
y3_pred=svmodel2.predict(x_test)
y3_pred

from sklearn import metrics
metrics.accuracy_score(y_test,y3_pred)


1.0

In [ ]:
# Parameter Gamma
from sklearn.svm import SVC
svmodel3=SVC(kernel='rbf',gamma=15,C=7)
svmodel3.fit(x_train,y_train)


SVC(C=7, gamma=15)

In [ ]:
y4_pred=svmodel3.predict(x_test)
metrics.accuracy_score(y_test,y4_pred)


0.2631578947368421

In [ ]:
from sklearn.svm import SVC
svmodel3=SVC(kernel='rbf',gamma=1,C=7)
svmodel3.fit(x_train,y_train)


SVC(C=7, gamma=1)

In [ ]:
y4_pred=svmodel3.predict(x_test)
metrics.accuracy_score(y_test,y4_pred)

0.9210526315789473