In [ ]:
 #Resources that would help
#https://numpy.org/doc/stable/user/quickstart.html
#https://www.w3schools.com/python/numpy/numpy_getting_started.asp 

In [ ]:
import numpy as np
#0-D array
arr=np.array(55)
print(arr)

55


In [ ]:
np.__version__
#1-D array or uni-dimensional
arr=np.array([1,2,3,4,5])
print(arr)
type(arr)


[1 2 3 4 5]


numpy.ndarray

In [ ]:
#Use a list to create a NumPy array Course, rollno, age and weight
a=['MCA',55,24,72.5]
arr=np.array(a)
print(arr)
type(a)
type(arr)


['MCA' '55' '24' '72.5']


numpy.ndarray

In [ ]:
#Use a tuple to create a NumPy array
arr=np.array((1,2,3,4,5))
print(arr)
type(arr)

[1 2 3 4 5]


numpy.ndarray

In [ ]:
#Assignment
#1. Create a tuple T1 and assign a tuple to it. #2. Create array by using T1. #3. Check its type
T1=(1,2,3,4,5)
arr=np.array(T1)
type(arr)


numpy.ndarray

In [ ]:
#2-D array #Size must be same of both otherwise NumPy will consider as a normal object
arr=np.array([[1,2,3],[4,5,6]])
arr.shape

(2, 3)

In [ ]:
arr=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr)
arr.shape

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


(2, 2, 3)

In [ ]:
#Array indexing
#Get the first element from the following array:
arr=np.array([1,2,3,4])
arr[0]

#Get the third element from the same array:
arr[2]

#Get second and fourth elements from the following array and add them.
second_element = arr[1]
fourth_element = arr[3]
print(second_element + fourth_element)

6


In [ ]:
#Access the element on the first row, second column
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr)
arr[0,1]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


2

In [ ]:
#Access the element on the 2nd row, 5th column
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
arr[1,4]

10

In [ ]:
#Access the third element of the second array of the first array
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr[0,1,2]


6

In [ ]:
#Access the second element of the first array of the second array
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr[1,0,1]


8

In [ ]:
#Access the second element of the second array of the second array
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr[1,1,1]

11