In [ ]:
import numpy as np
#Slice elements from index 1 to 5 from the following array:
arr=np.array([1,2,3,4,5,6,7])
arr[1:5]

array([2, 3, 4, 5])

In [ ]:
#Slice elements from index 4 to the end of the array:
arr=np.array([1,2,3,4,5,6,7])
arr[4:]

array([5, 6, 7])

In [ ]:
#Slice elements from the beginning to index 4:
arr=np.array([1,2,3,4,5,6,7])
arr[:4]

array([1, 2, 3, 4])

In [ ]:
#Return every other element from index 1 to index 5:
arr=np.array([1,2,3,4,5,6,7])
arr[1:5:2]

array([2, 4])

In [ ]:
#Slice from the index 3 from the end to index 1 from the end:
arr=np.array([1,2,3,4,5,6,7])
arr[-3:-1]

array([5, 6])

In [ ]:
#Return every other element from the entire array:
arr=np.array([1,2,3,4,5,6,7])
arr[::2]

array([1, 3, 5, 7])

In [ ]:
#From the second element, slice elements from index 1 to index 4:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
arr[1,1:4]

array([7, 8, 9])

In [ ]:
#Array Creation
#The function creates an array full of zeros
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
#The function creates an array full of ones
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
#The function empty creates an array whose initial content is random and depends on the state of the memory
np.empty((2,3))

array([[4.71008253e-310, 0.00000000e+000, 6.60198788e-310],
       [6.60205063e-310, 6.60198788e-310, 6.60205063e-310]])

In [ ]:
#np.eye() -Return a 2-D array with ones on the diagonal and zeros elsewhere
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
#Basic Operations
A=np.array([[1,1],[0,1]])
B=np.array([[2,0],[3,4]])

A*B  #elementwise product

array([[2, 0],
       [0, 4]])

In [ ]:
#Basic Operations
A=np.array([[1,1],[0,1]])
B=np.array([[2,0],[3,4]])

A@B  #matrix product

array([[5, 4],
       [3, 4]])

In [ ]:
#Basic Operations
A=np.array([[1,1],[0,1]])
B=np.array([[2,0],[3,4]])

A.dot(B)  #another way of matrix product

array([[5, 4],
       [3, 4]])